# modules/report.py

from fpdf import FPDF
from datetime import datetime
import os

class ReconReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_fill_color(30, 30, 30)
        self.set_text_color(0, 200, 100)
        self.cell(0, 15, "OSINT RECON REPORT", align="C", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Generated by OSINT Recon Tool | Page {self.page_no()}", align="C")

    def section_title(self, title):
        self.set_font("Helvetica", "B", 12)
        self.set_fill_color(50, 50, 50)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, f"  {title}", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def add_row(self, label, value):
        self.set_font("Helvetica", "B", 10)
        self.set_fill_color(240, 240, 240)
        self.cell(50, 8, f"  {label}", fill=True)
        self.set_font("Helvetica", "", 10)
        self.set_fill_color(255, 255, 255)
        # Clean value - remove non-latin1 characters
        clean_value = str(value).encode("latin-1", "replace").decode("latin-1")
        self.cell(0, 8, f"  {clean_value}", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def add_list_item(self, item, found=None):
        self.set_font("Helvetica", "", 10)
        if found is True:
            self.set_text_color(0, 150, 0)
            prefix = "[FOUND]"
        elif found is False:
            self.set_text_color(200, 0, 0)
            prefix = "[NOT FOUND]"
        else:
            self.set_text_color(50, 50, 50)
            prefix = "  ->"
        clean_item = str(item).encode("latin-1", "replace").decode("latin-1")
        self.cell(0, 7, f"  {prefix} {clean_item}", new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)


def generate_report(target, whois_data, dns_data, ip, geo, rep, subdomains, email_result, social_results):
    """Generate a full PDF report of recon results"""

    pdf = ReconReport()
    pdf.add_page()

    # ── META INFO ──
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 7, f"Target Domain : {target}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, f"Generated     : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)

    # ── WHOIS ──
    pdf.section_title("WHOIS INFORMATION")
    if "error" not in whois_data:
        pdf.add_row("Registrar", whois_data.get("registrar", "N/A"))
        pdf.add_row("Country", whois_data.get("country", "N/A"))
        pdf.add_row("Created", whois_data.get("creation_date", "N/A"))
        pdf.add_row("Expires", whois_data.get("expiration_date", "N/A"))
        ns = ", ".join(whois_data.get("name_servers", [])[:3]) or "N/A"
        pdf.add_row("Name Servers", ns)
    else:
        pdf.add_row("Error", whois_data.get("error", "Unknown"))
    pdf.ln(3)

    # ── DNS ──
    pdf.section_title("DNS RECORDS")
    for record_type, values in dns_data.items():
        if values:
            pdf.add_row(record_type, ", ".join(values[:3]))
    pdf.ln(3)

    # ── IP GEOLOCATION ──
    pdf.section_title("IP GEOLOCATION")
    if ip:
        pdf.add_row("Resolved IP", ip)
        if "error" not in geo:
            pdf.add_row("Country", geo.get("country", "N/A"))
            pdf.add_row("City", f"{geo.get('city', 'N/A')}, {geo.get('region', 'N/A')}")
            pdf.add_row("ISP", geo.get("isp", "N/A"))
            pdf.add_row("Organization", geo.get("org", "N/A"))
            pdf.add_row("Coordinates", f"{geo.get('lat')}, {geo.get('lon')}")
            pdf.add_row("Timezone", geo.get("timezone", "N/A"))
    pdf.ln(3)

    # ── IP REPUTATION ──
    pdf.section_title("IP REPUTATION")
    if rep and "error" not in rep:
        pdf.add_row("Is Proxy/VPN", "YES" if rep.get("is_proxy") else "NO")
        pdf.add_row("Is Hosting", "YES" if rep.get("is_hosting") else "NO")
        pdf.add_row("Is Mobile", "YES" if rep.get("is_mobile") else "NO")
    pdf.ln(3)

    # ── SUBDOMAINS ──
    pdf.section_title(f"SUBDOMAINS ({len(subdomains)} found)")
    if subdomains:
        for sub in subdomains[:20]:
            pdf.add_list_item(sub)
    else:
        pdf.add_list_item("No subdomains found")
    pdf.ln(3)

    # ── EMAIL BREACH ──
    pdf.section_title("EMAIL BREACH CHECK")
    if email_result:
        if "error" in email_result:
            pdf.add_row("Status", f"Error: {email_result['error']}")
        elif email_result.get("breached"):
            pdf.add_row("Email", email_result.get("email", "N/A"))
            pdf.add_row("Status", f"BREACHED - Found in {email_result['breach_count']} breaches")
            for breach in email_result.get("breaches", [])[:5]:
                pdf.add_list_item(breach)
        else:
            pdf.add_row("Email", email_result.get("email", "N/A"))
            pdf.add_row("Status", "No breaches found")
    else:
        pdf.add_row("Status", "Skipped")
    pdf.ln(3)

    # ── SOCIAL MEDIA ──
    pdf.section_title("SOCIAL MEDIA SCAN")
    if social_results:
        for platform, data in social_results.items():
            pdf.add_list_item(f"{platform:15} {data['url']}", found=data["found"])
    else:
        pdf.add_row("Status", "Skipped")
    pdf.ln(3)

    # ── SAVE ──
    os.makedirs("output", exist_ok=True)
    filename = f"output/recon_{target}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    pdf.output(filename)
    return filename